CREATE VIEW VIEW_USER_INFORMATION AS
SELECT U.USER_ID AS USER_ID,
       U.FIRST_NAME AS FIRST_NAME,
       U.LAST_NAME AS LAST, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM Users U

CREATE VIEW VIEW_ARE_FRIENDS AS

CREATE VIEW VIEW_PHOTO_INFORMATION AS

CREATE VIEW VIEW_EVENT_INFORMATION AS

CREATE VIEW VIEW_TAG_INFORMATION AS