CREATE TABLE Users (
  USER_ID NUMBER,
  FIRST_NAME VARCHAR2(100) NOT NULL,
  LAST_NAME VARCHAR2(100) NOT NULL,
  YEAR_OF_BIRTH INTEGER,
  MONTH_OF_BIRTH INTEGER,
  DAY_OF_BIRTH INTEGER,
  GENDER VARCHAR2(100),
  PRIMARY KEY(USER_ID),
)

/*
  IMPLEMENT FRIENDS TRIGGER!!!!
*/
CREATE TABLE Friends (
  USER1_ID NUMBER,
  USER2_ID NUMBER,
  FOREIGN KEY(USER1_ID, USER2_ID) REFERENCES Users,
)

CREATE TABLE Cities (
  CITY_ID INTEGER,
  CITY_NAME VARCHAR2(100) NOT NULL,
  STATE_NAME VARCHAR2(100) NOT NULL,
  COUNTRY_NAME VARCHAR2(100) NOT NULL,
  PRIMARY KEY(CITY_ID),
)

CREATE TABLE User_Current_Cities (
  USER_ID NUMBER,
  CURRENT_CITY_ID INTEGER,
  FOREIGN KEY(USER_ID) REFERENCES Users,
  FOREIGN KEY(CURRENT_CITY_ID) REFERENCES Cities,
)

CREATE TABLE User_Hometown_Cities (
  USER_ID NUMBER,
  HOMETOWN_CITY_ID INTEGER,
  FOREIGN KEY(USER_ID) REFERENCES Users,
  FOREIGN KEY(HOMETOWN_CITY_ID) REFERENCES Cities, 
)

CREATE TABLE Messages (
  MESSAGE_ID NUMBER,
  SENDER_ID NUMBER,
  RECEIVER_ID NUMBER,
  MESSAGE_CONTENT VARCHAR2(2000) NOT NULL,
  SENT_TIME TIMESTAMP NOT NULL,
  PRIMARY KEY(MESSAGE_ID),
  FOREIGN KEY(SENDER_ID) REFERENCES Users,
  FOREIGN KEY(RECEIVER_ID) REFERENCES Users,
)

CREATE TABLE Programs (
  PROGRAM_ID INTEGER,
  INSTITUTION VARCHAR2(100) NOT NULL,
  CONCENTRATION VARCHAR2(100) NOT NULL,
  DEGREE VARCHAR2(100) NOT NULL,
  PRIMARY KEY(PROGRAM_ID),
)

CREATE TABLE Education (
  USER_ID NUMBER,
  PROGRAM_ID INTEGER,
  PROGRAM_YEAR INTEGER NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES Users,
  FOREIGN KEY(PROGRAM_ID) REFERENCES Programs,
)

CREATE TABLE User_Events (
  EVENT_ID NUMBER,
  EVENT_CREATOR_ID NUMBER,
  EVENT_NAME VARCHAR2(100) NOT NULL,
  EVENT_TAGLINE VARCHAR2(100),
  EVENT_DESCRIPTION VARCHAR2(100),
  EVENT_HOST VARCHAR2(100),
  EVENT_TYPE VARCHAR2(100),
  EVENT_SUBTYPE VARCHAR2(100),
  EVENT_ADDRESS VARCHAR2(2000),
  EVENT_CITY_ID INTEGER,
  EVENT_START_TIME TIMESTAMP,
  EVENT_END_TIME TIMESTAMP,
  PRIMARY KEY(EVENT_ID),
  FOREIGN KEY(EVENT_CREATOR_ID) REFERENCES Users,
  FOREIGN KEY(EVENT_CITY_ID) REFERENCES Cities,
)

CREATE TABLE Participants (
  EVENT_ID NUMBER,
  USER_ID NUMBER,
  CONFIRMATION VARCHAR2(100) NOT NULL,
  FOREIGN KEY(EVENT_ID) REFERENCES User_Events,
  FOREIGN KEY(USER_ID) REFERENCES Users,
)

CREATE TABLE Albums (
  ALBUM_ID NUMBER,
  ALBUM_OWNER_ID NUMBER,
  ALBUM_NAME VARCHAR2(100) NOT NULL,
  ALBUM_CREATED_TIME TIMESTAMP NOT NULL,
  ALBUM_MODIFIED_TIME TIMESTAMP,
  ALBUM_LINK VARCHAR2(100) NOT NULL,
  ALBUM_VISIBILITY VARCHAR2(100) NOT NULL,
  COVER_PHOTO_ID NUMBER,
  PRIMARY KEY(ALBUM_ID),
  FOREIGN KEY(ALBUM_OWNER_ID) REFERENCES Users,
  FOREIGN KEY(COVER_PHOTO_ID) REFERENCES Photos,
)

CREATE TABLE Photos (
  PHOTO_ID NUMBER,
  ALBUM_ID NUMBER,
  PHOTO_CAPTION VARCHAR2(2000),
  PHOTO_CREATED_TIME TIMESTAMP NOT NULL,
  PHOTO_MODIFIED_TIME TIMESTAMP,
  PHOTO_LINK VARCHAR2(2000) NOT NULL,
  PRIMARY KEY(PHOTO_ID),
  FOREIGN KEY(ALBUM_ID) REFERENCES Albums,
)

CREATE TABLE Tags (
  TAG_PHOTO_ID NUMBER,
  TAG_SUBJECT_ID NUMBER,
  TAG_CREATED_TIME TIMESTAMP NOT NULL,
  TAG_X NUMBER NOT NULL,
  TAG_Y NUMBER NOT NULL,
  FOREIGN KEY(TAG_PHOTO_ID) REFERENCES Photos,
  FOREIGN KEY(TAG_SUBJECT_ID) REFERENCES Users,
)