CREATE VIEW VIEW_USER_INFORMATION AS
    SELECT
           U.USER_ID AS USER_ID,
           U.FIRST_NAME AS FIRST_NAME,
           U.LAST_NAME AS LAST_NAME,
           U.YEAR_OF_BIRTH AS YEAR_OF_BIRTH,
           U.MONTH_OF_BIRTH AS MONTH_OF_BIRTH,
           U.DAY_OF_BIRTH AS DAY_OF_BIRTH,
           U.GENDER AS GENDER,
           C.CITY_NAME AS CURRENT_CITY,
           C.STATE_NAME AS CURRENT_STATE,
           C.COUNTRY_NAME AS CURRENT_COUNTRY,
           C.CITY_NAME AS HOMETOWN_CITY,
           C.STATE_NAME AS HOMETOWN_STATE,
           C.COUNTRY_NAME AS HOMETOWN_COUNTRY,
           P.INSTITUTION AS INSTITUTION_NAME,
           E.PROGRAM_YEAR AS PROGRAM_YEAR,
           P.CONCENTRATION AS PROGRAM_CONCENTRATION,
           P.DEGREE AS PROGRAM_DEGREE
    FROM
         Users U, Cities C, User_Current_Cities UC, User_Hometown_Cities UH, Programs P, Education E
    WHERE
          U.USER_ID = UC.USER_ID AND
          U.USER_ID = UH.USER_ID AND
          C.CITY_ID = UC.CURRENT_CITY_ID AND
          C.CITY_ID = UH.HOMETOWN_CITY_ID AND
          U.USER_ID = E.USER_ID AND
          E.PROGRAM_ID = P.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS
    SELECT
           USER1_ID,
           USER2_ID
    FROM
         Friends;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
    SELECT
           A.ALBUM_ID AS ALBUM_ID,
           A.ALBUM_OWNER_ID AS OWNER_ID,
           A.COVER_PHOTO_ID AS COVER_PHOTO_ID,
           A.ALBUM_NAME AS ALBUM_NAME,
           A.ALBUM_CREATED_TIME AS ALBUM_CREATED_TIME,
           A.ALBUM_MODIFIED_TIME AS ALBUM_MODIFIED_TIME,
           A.ALBUM_LINK AS ALBUM_LINK,
           A.ALBUM_VISIBILITY AS ALBUM_VISIBILITY,
           P.PHOTO_ID AS PHOTO_ID,
           P.PHOTO_CAPTION AS PHOTO_CAPTION,
           P.PHOTO_CREATED_TIME AS PHOTO_CREATED_TIME,
           P.PHOTO_MODIFIED_TIME AS PHOTO_MODIFIED_TIME,
           P.PHOTO_LINK AS PHOTO_LINK
    FROM
         Albums A, Photos P
    WHERE
          P.ALBUM_ID = A.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
    SELECT E.EVENT_ID AS EVENT_ID,
           E.EVENT_CREATOR_ID AS EVENT_CREATOR_ID,
           E.EVENT_NAME AS EVENT_NAME,
           E.EVENT_TAGLINE AS EVENT_TAGLINE,
           E.EVENT_DESCRIPTION AS EVENT_DESCRIPTION,
           E.EVENT_HOST AS EVENT_HOST,
           E.EVENT_TYPE AS EVENT_TYPE,
           E.EVENT_SUBTYPE AS EVENT_SUBTYPE,
           E.EVENT_ADDRESS AS EVENT_ADDRESS,
           C.CITY_NAME AS EVENT_CITY,
           C.STATE_NAME AS EVENT_STATE,
           C.COUNTRY_NAME AS EVENT_COUNTRY,
           E.EVENT_START_TIME AS EVENT_START_TIME,
           E.EVENT_END_TIME AS EVENT_END_TIME
    FROM
         User_Events E, Cities C
    WHERE E.EVENT_CITY_ID = C.CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
    SELECT TAG_PHOTO_ID AS PHOTO_ID,
           TAG_SUBJECT_ID,
           TAG_CREATED_TIME,
           TAG_X AS TAG_X_COORDINATE,
           TAG_Y AS TAG_Y_COORDINATE
    FROM Tags;